# Generated by Django 5.0.4 on 2024-07-05 17:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='block_employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.FileField(upload_to='')),
                ('cv', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('job', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=20)),
                ('number', models.IntegerField()),
                ('user_name', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20, unique=True)),
                ('c_password', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='emp_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.FileField(upload_to='')),
                ('cv', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('job', models.CharField(choices=[('carpenter', 'carpenter'), ('Furniture Mover', 'Furniture Mover'), ('tank cleaner', 'tank cleaner'), ('Plumber', 'Plumber'), ('cctv technician', 'cctv technician')], default='select', max_length=150, null=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('address', models.CharField(max_length=20)),
                ('number', models.IntegerField()),
                ('user_name', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20, unique=True)),
                ('c_password', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('Free', 'Free'), ('In work', 'In work'), ('Off duty', 'Off duty')], default='Free', max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('frimg', models.FileField(upload_to='')),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('district', models.CharField(max_length=200, null=True)),
                ('pin_code', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=500)),
                ('number', models.IntegerField()),
                ('user_name', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20, unique=True)),
                ('c_password', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='verify_emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.FileField(upload_to='')),
                ('cv', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('job', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=20)),
                ('number', models.IntegerField()),
                ('user_name', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20, unique=True)),
                ('c_password', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='w_categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=20)),
                ('frimg', models.FileField(upload_to='')),
                ('s_price', models.IntegerField()),
                ('content', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=4)),
                ('emp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.emp_reg')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.register')),
            ],
        ),
        migrations.CreateModel(
            name='booked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.IntegerField(unique=True)),
                ('booked_name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('number', models.IntegerField()),
                ('state', models.CharField(max_length=200, null=True)),
                ('district', models.CharField(max_length=200, null=True)),
                ('pin_code', models.IntegerField(null=True)),
                ('date', models.DateField(default=datetime.datetime.today, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('b_s_name', models.CharField(max_length=200, null=True)),
                ('b_s_price', models.IntegerField(null=True)),
                ('payment_mode', models.CharField(default='Razor_pay', max_length=200, null=True)),
                ('emp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.emp_reg')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.register')),
            ],
        ),
        migrations.CreateModel(
            name='adminpassbookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.IntegerField(unique=True)),
                ('booked_name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('number', models.IntegerField()),
                ('state', models.CharField(max_length=200, null=True)),
                ('district', models.CharField(max_length=200, null=True)),
                ('pin_code', models.IntegerField(null=True)),
                ('date', models.DateField(default=datetime.datetime.today, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('b_s_name', models.CharField(max_length=200, null=True)),
                ('b_s_price', models.IntegerField(null=True)),
                ('payment_mode', models.CharField(default='Razor_pay', max_length=200, null=True)),
                ('status', models.CharField(choices=[('Finished', 'Finished'), ('pending', 'pending'), ('Cancelled', 'Cancelled')], default='pending', max_length=150, null=True)),
                ('emp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.emp_reg')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.register')),
            ],
        ),
        migrations.CreateModel(
            name='u_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.CharField(max_length=200)),
                ('radio_c', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('user_name', models.CharField(max_length=200, null=True)),
                ('s_name', models.CharField(max_length=200, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.register')),
            ],
        ),
        migrations.CreateModel(
            name='bookings',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('b_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('number', models.IntegerField()),
                ('state', models.CharField(max_length=200, null=True)),
                ('district', models.CharField(max_length=200, null=True)),
                ('pin_code', models.IntegerField(null=True)),
                ('date', models.DateField(default=datetime.datetime.today, null=True)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Finished', 'Finished'), ('pending', 'pending'), ('Cancelled', 'Cancelled')], default='pending', max_length=150, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('payment_status', models.CharField(max_length=200, null=True)),
                ('emp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.emp_reg')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.register')),
                ('review', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.u_review')),
                ('w', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.w_categories')),
            ],
        ),
    ]
